# Generated by Django 5.0.7 on 2024-07-13 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=3, unique=True, verbose_name='Short Name')),
                ('rate_to_usd', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rate To USD')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Rate To USD',
                'verbose_name_plural': 'Rates To USD',
            },
        ),
    ]
