# Generated by Django 5.0.7 on 2024-07-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='short_name',
            field=models.CharField(choices=[('RUB', 'Рубли'), ('USD', 'Доллары'), ('KZT', 'Тенге')], max_length=3, verbose_name='Short Name'),
        ),
    ]
